CREATE DATABASE IF NOT EXISTS company;
USE company;

DROP TABLE IF EXISTS employee;
CREATE TABLE employee (
    id INT(11) NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(64) DEFAULT NULL,
    last_name VARCHAR(64) DEFAULT NULL,
    position VARCHAR(64) DEFAULT NULL,
    salary DECIMAL(10, 2) DEFAULT 0.00,
    PRIMARY KEY(id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
